# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:55
from __future__ import unicode_literals

from django.db import migrations
from pathlib import Path

class Migration(migrations.Migration):
    """
    Populate calc columns
    """

    dependencies = [
        ('dcal', '0002_auto_20161203_1631'),
    ]

    file_sql = [Path(file).read_text() for file in sorted(Path('./sql/').glob('calc_*.sql'))]
    if not file_sql:
        raise FileNotFoundError

    operations = [
        migrations.RunSQL(sql) for sql in file_sql
    ]

